name: CI

on:
  push:
  pull_request:

jobs:
  tests:
    name: Tests on PHP ${{ matrix.php }}
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        php: ['7.2', '7.3', '7.4']
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - uses: shivammathur/setup-php@2.9.0
        with:
          php-version: ${{ matrix.php }}
      - name: Install dependencies
        run: composer install
      - name: Configure PHPUnit problem matchers
        run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"
      - name: Run tests
        run: ./vendor/bin/phpunit
